#%RAML 1.0 DataType
properties:
  firstName :
    required: true
    type: string
    maxLength: 30
    minLength: 2
  lastName :
    required: true
    type: string
    maxLength: 30
    minLength: 2
  phoneNum:
    type: string
    required: true
  email:
    type: string
    required: false
    maxLength: 20
    minLength: 2
